In [69]:
import imblearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [71]:
churnData=pd.read_csv('Customer-Churn.csv')
churnData.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0              No  Month-to-month           29.85        29.85    No  
1              No        One year           56.95       1889.5    No  
2              No  Month-to-month           53.85       108.15   Yes  
3              No        One year           42.30      1840.75    No  
4              No  Month-to-month           70.70       151.65   Yes

In [72]:
#task is to build a machine learning model that will help the company identify customers that are more likely to default/churn 
#and thus prevent losses from such customers

In [73]:
churnData.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [74]:
# Convert this column of TotalCharges into numeric type using pd.to_numeric function.
churnData['TotalCharges'] = pd.to_numeric(churnData['TotalCharges'],errors='coerce')


In [75]:
churndata['TotalCharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [76]:
# Check for null values in the dataframe. Replace the null values.

In [77]:
churndata.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [78]:
churnData["TotalCharges"] = churnData["TotalCharges"].replace(" ", 0)

In [79]:
churnData.isna().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [80]:
mean_val = churnData['TotalCharges'].mean()
churnData['TotalCharges'].fillna(mean_val, inplace=True)

In [81]:
churnData.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [82]:
churnData.shape

(7043, 16)

In [83]:
churnData["Churn"] = churnData["Churn"].replace({'No':0, 'Yes':1})

In [84]:
# tenure, SeniorCitizen, MonthlyCharges and TotalCharges:
numerical = churnData.select_dtypes("number")
numerical

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Churn
0                 0       1           29.85         29.85      0
1                 0      34           56.95       1889.50      0
2                 0       2           53.85        108.15      1
3                 0      45           42.30       1840.75      0
4                 0       2           70.70        151.65      1
...             ...     ...             ...           ...    ...
7038              0      24           84.80       1990.50      0
7039              0      72          103.20       7362.90      0
7040              0      11           29.60        346.45      0
7041              1       4           74.40        306.60      1
7042              0      66          105.65       6844.50      0

[7043 rows x 5 columns]

In [85]:
from sklearn import preprocessing

y = numerical['Churn']
X = numerical.drop(['Churn'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [86]:
# Scaling data
# Scale the features either by using normalizer or a standard scaler.
# all features are numeric, so no need to split into _num and _cat
transformer = MinMaxScaler().fit(X_train) # need to keep transformer
X_train_normalized = transformer.transform(X_train)
X_train_norm = pd.DataFrame(X_train_normalized, columns=X_train.columns)

In [88]:
transformer = MinMaxScaler().fit(X_test) 
X_test_normalized = transformer2.transform(X_test)
X_test_norm = pd.DataFrame(X_test_normalized, columns=X_test.columns)

In [89]:
X_test_norm.head()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges
0            0.0  0.013889        0.060970      0.000682
1            0.0  0.569444        0.065467      0.112965
2            0.0  0.722222        0.006497      0.117039
3            0.0  0.013889        0.576212      0.006639
4            0.0  0.930556        0.318341      0.374551

In [90]:
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True) 

In [91]:
LR = LogisticRegression(random_state=0, solver='lbfgs').fit(X_train_norm, y_train)

In [92]:
LR.score(X_test_norm, y_test)

0.8041163946061036

In [93]:
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [97]:
pred = LR.predict(X_test_norm)

print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))
print("Accuracy: ",accuracy_score(y_test,pred))

precision:  0.6947791164658634
recall:  0.46380697050938335
f1:  0.5562700964630225
Accuracy:  0.8041163946061036


In [95]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[960,  76],
       [200, 173]])

In [ ]:
# the model is not good

In [116]:
# Oversampling
from sklearn.utils import resample


In [117]:
train1 = pd.concat([X_train_norm, y_train],axis=1)
train1.head()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges  Churn
0            0.0  0.291667        0.464375      0.152089      0
1            0.0  0.750000        0.786746      0.589736      0
2            0.0  0.013889        0.051819      0.000537      1
3            0.0  0.055556        0.517688      0.025288      1
4            0.0  0.000000        0.434978      0.261309      0

In [118]:
no_churn = train1 [train1 ['Churn']==0]
yes_churn = train1 [train1 ['Churn']==1]

In [119]:
display(no_churn.shape)
display(yes_churn.shape)

(4138, 5)

(1496, 5)

In [120]:
# oversample minority
yes_churn_oversampled = resample(yes_churn, #<- sample from here
                                    replace=True, #<- we need replacement, since we don't have enough data otherwise
                                    n_samples = len(no_churn),#<- make both sets the same size
                                    random_state=0)

In [121]:
# both sets are now of a reasonable size
display(no_churn.shape)
display(yes_churn_oversampled.shape)

(4138, 5)

(4138, 5)

In [122]:
train_oversampled = pd.concat([no_churn,yes_churn_oversampled],axis=0)
train_oversampled.tail()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges  Churn
54              0.0  0.375000        0.760339      0.312232      1
1364            1.0  0.055556        0.564524      0.034958      1
4912            0.0  0.166667        0.811659      0.140740      1
4765            1.0  0.291667        0.782760      0.232114      1
1522            0.0  0.111111        0.848032      0.095604      1

In [123]:
y_train_over = train_oversampled['Churn'].copy()
X_train_over = train_oversampled.drop('Churn',axis = 1).copy()

In [129]:
LR = LogisticRegression(max_iter=1000)
LR.fit(X_train_over, y_train_over)
pred = LR.predict(X_test_norm)
print('Accuracy is ', LR.score(X_test_norm, y_test))
print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

Accuracy is  0.7437899219304471
precision:  0.5107913669064749
recall:  0.7613941018766756
f1:  0.6114101184068891


In [130]:
confusion_matrix(y_test,pred)

array([[764, 272],
       [ 89, 284]])

In [131]:
#Downsampling
# undersample majority
no_churn_undersampled = resample(no_churn, #<- downsample from here
                                    replace=False, #<- no need to reuse data now, we have an abundance
                                    n_samples = len(yes_churn),
                                    random_state=0)

In [133]:
# both sets are the same size
# small, but balanced, and no repeated data
display(yes_churn.shape)
display(no_churn_undersampled.shape)

(1496, 5)

(1496, 5)

In [134]:
train_undersampled = pd.concat([yes_churn,no_churn_undersampled])
train_undersampled.head()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges  Churn
2             0.0  0.013889        0.051819      0.000537      1
3             0.0  0.055556        0.517688      0.025288      1
8             0.0  0.263889        0.213254      0.082454      1
10            1.0  0.291667        0.506726      0.168007      1
26            1.0  0.111111        0.735924      0.082062      1

In [137]:
y_train_under = train_undersampled['Churn'].copy()
X_train_under = train_undersampled.drop('Churn',axis = 1).copy()

In [138]:
LR = LogisticRegression(max_iter=1000)
LR.fit(X_train_under, y_train_under)
pred = LR.predict(X_test_norm)
print('Accuracy is ', LR.score(X_test_norm, y_test))
print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

Accuracy is  0.7437899219304471
precision:  0.5107142857142857
recall:  0.7667560321715817
f1:  0.6130760986066451


In [139]:
confusion_matrix(y_test,pred)

array([[762, 274],
       [ 87, 286]])